name: Build and Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build:new

      - name: Zip distribution files
        run: |
          cd dist/
          zip -r ../extension-dist.zip ./*

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}

          name: Release ${{ github.ref_name }}

          draft: false

          files: extension-dist.zip

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
